artifact_location: file:///home/runner/work/Workflow_CI/Workflow_CI/MLProject/mlruns/704882880621800439
creation_time: 1766159964517
experiment_id: '704882880621800439'
last_update_time: 1766159964517
lifecycle_stage: active
name: BMW_Price_Prediction_Workflow
