artifact_location: file:///home/runner/work/Workflow_CI/Workflow_CI/MLProject/mlruns/0
creation_time: 1766159964509
experiment_id: '0'
last_update_time: 1766159964509
lifecycle_stage: active
name: Default
