artifact_location: file:///home/runner/work/Workflow_CI/Workflow_CI/MLProject/mlruns/956118021826454420
creation_time: 1766158070554
experiment_id: '956118021826454420'
last_update_time: 1766158070554
lifecycle_stage: active
name: BMW_Price_Prediction_Workflow
